#include <iostream.h>
#include<conio.h>
int main()
{
	clrscr();
	int z = 10;
	if (z > 10)
	{
	cout << "Lol ok";
	}
	else
	{
	cout<<"Error!!";
	}
getch();
return 0;
}

//	if (z>10)
//		{
//			cout<<"Both x and z are greater than 10"<< endl;
//			if (z % 3 == 0)
//			{
//			cout<<"Z is a multiple of 2" << endl;
//			}
//			else if (z % 5 == 0)
//			{
//			cout<<"Z is a multiple of 5"<< endl;
//			}
//		}
//		else
//		{
//		cout << "NICE one";
//		}
//	}